# NumPy Fonksiyonları ile Örnekler

Bu notebook, NumPy kütüphanesinin 10 önemli fonksiyonunu açıklamaktadır. Aşağıda sırasıyla `np.array`, `np.arange`, `np.linspace`, `np.reshape`, `np.zeros`, `np.ones`, `np.eye`, `np.sum`, `np.mean` ve `np.dot` fonksiyonlarının ne işe yaradıkları ve örnek kullanımları yer almaktadır.

In [1]:
import numpy as np

## 1. np.array

`np.array` fonksiyonu, verilen liste veya benzeri veri yapılarından NumPy dizisi (array) oluşturmak için kullanılır.

In [4]:
# np.array örneği
arr = np.array([1, 2, 3, 4, 5])
print('np.array örneği:', arr)

np.array örneği: [1 2 3 4 5]


## 2. np.arange

`np.arange` fonksiyonu, belirli bir aralıkta eşit aralıklarla sayıların bulunduğu bir NumPy dizisi oluşturur. Python'un yerleşik `range` fonksiyonuna benzer ancak dizi döndürür.

In [7]:
# np.arange örneği
arr = np.arange(0, 10, 2)  # 0'dan 10'a kadar 2'şer artarak
print('np.arange örneği:', arr)

np.arange örneği: [0 2 4 6 8]


## 3. np.linspace

`np.linspace` fonksiyonu, başlangıç ve bitiş değeri arasında, belirli sayıda eşit aralıklı sayı üretir.

In [10]:
# np.linspace örneği
arr = np.linspace(0, 1, 5)  # 0 ile 1 arasında 5 eşit parçaya böler
print('np.linspace örneği:', arr)

np.linspace örneği: [0.   0.25 0.5  0.75 1.  ]


## 4. np.reshape

`np.reshape` fonksiyonu, mevcut bir dizinin boyutlarını yeniden düzenlemek için kullanılır. Bu sayede diziyi istenilen şekle sokabilirsiniz.

In [13]:
# np.reshape örneği
arr = np.arange(6)  # 0'dan 5'e kadar sayı içeren dizi
reshaped_arr = arr.reshape((2, 3))  # 2 satır, 3 sütunluk matris
print('np.reshape örneği:\n', reshaped_arr)

np.reshape örneği:
 [[0 1 2]
 [3 4 5]]


## 5. np.zeros

`np.zeros` fonksiyonu, belirli boyutlarda tüm elemanları 0 olan bir dizi oluşturur.

In [16]:
# np.zeros örneği
zeros_arr = np.zeros((3, 3))  # 3x3 boyutunda sıfır matris
print('np.zeros örneği:\n', zeros_arr)

np.zeros örneği:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 6. np.ones

`np.ones` fonksiyonu, belirli boyutlarda tüm elemanları 1 olan bir dizi oluşturur.

In [19]:
# np.ones örneği
ones_arr = np.ones((2, 4))  # 2x4 boyutunda 1'lerden oluşan matris
print('np.ones örneği:\n', ones_arr)

np.ones örneği:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 7. np.eye

`np.eye` fonksiyonu, kare matris şeklinde birim (identity) matris oluşturur. Birim matriste köşegen elemanlar 1, diğerleri 0’dır.

In [22]:
# np.eye örneği
identity = np.eye(4)  # 4x4 birim matris
print('np.eye örneği:\n', identity)

np.eye örneği:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 8. np.sum

`np.sum` fonksiyonu, bir dizinin tüm elemanlarının toplamını veya belirli bir eksen boyunca toplamını hesaplar.

In [25]:
# np.sum örneği
arr = np.array([[1, 2, 3], [4, 5, 6]])
total = np.sum(arr)
print('np.sum örneği, tüm elemanların toplamı:', total)

np.sum örneği, tüm elemanların toplamı: 21


## 9. np.mean

`np.mean` fonksiyonu, bir dizinin ortalamasını hesaplamak için kullanılır.

In [28]:
# np.mean örneği
arr = np.array([10, 20, 30, 40, 50])
mean_val = np.mean(arr)
print('np.mean örneği, ortalama değer:', mean_val)

np.mean örneği, ortalama değer: 30.0


## 10. np.dot

`np.dot` fonksiyonu, iki dizinin noktasal (dot) çarpımını hesaplar. Bu fonksiyon, vektörlerin skaler çarpımını veya matris çarpımını yapmak için kullanılır.

In [31]:
# np.dot örneği
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print('np.dot örneği, noktasal çarpım:', dot_product)

np.dot örneği, noktasal çarpım: 32
